FROM php:8.2-apache

RUN apt-get update && apt-get install -y zip unzip

COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

WORKDIR /var/www/html


COPY composer.json ./


COPY . .


RUN composer dump-autoload --no-scripts --no-interaction

RUN chown -R www-data:www-data /var/www/html
